### ISSUE TITLE
Broken link in description

### ISSUE THREAD

**Issue by tnias** [haskellari/qc-instances#59]
Description in `quickcheck-instances.cabal` contains a broken link.

https://github.com/phadej/qc-instances/blob/42907c7b6921613c135c03cbb39b942a3b85d894/quickcheck-instances.cabal#L17

**Comment by phadej** [comment]
I'd drop that paragraph completely.

**Comment by phadej** [comment]
Done in https://github.com/haskellari/qc-instances/pull/83
