### ISSUE TITLE
Support GHC 9.0

### ISSUE THREAD

**Issue by ndmitchell** [haskellari/qc-instances#65]
Installing this with GHC 9.0 I get:

[__2] trying: quickcheck-instances-0.3.25.2 (dependency of extra *test)
[__3] next goal: base (dependency of extra)
[__3] rejecting: base-4.15.0.0/installed-4.15.0.0 (conflict:
quickcheck-instances => base>=4.5 && <4.15)

Seems you need to relax the base constraint.

**Comment by phadej** [comment]
Blocked on https://github.com/tibbe/hashable/issues/193

**Comment by phadej** [comment]
https://hackage.haskell.org/package/quickcheck-instances-0.3.25.2/revisions/
