### ISSUE TITLE
QuickCheck bounds are out-of-date

### ISSUE THREAD

**Issue by MaximilianAlgehed** [haskellari/qc-instances#96]
The latest hackage version of QuickCheck is 2.15 but the `.cabal` file here restricts the version to `<2.15`.

**Comment by phadej** [comment]
to `<2.15.0`

```
  build-depends:
    , QuickCheck  >=2.14.2   && <2.15.0
```

`2.15 < 2.15.0`.

**Comment by MaximilianAlgehed** [comment]
My bad... My god PVP is stupid...

**Comment by phadej** [comment]
It's not PVP fault. PVP actually says 

> A package version number SHOULD have the form A.B.C, and MAY optionally have any number of additional components, for example 2.1.0.4 ...

That's nitpicking, but as far as PVP semantics are considered, they always assume there is some `C`, there is no case for absent one. So there are no semantics specified for the allowed changes between `X.Y` and `X.Y.0(.W)`. I have to assume the worst.

It *could* mention that if `C` is absent, for the purpose of `C+1` cases, it should be assumed to be zero. (So `2.15 -> 2.15.0` cannot add anything, i.e. can only be mere patch release, like `2.15.0.3 -> 2.15.0.4`); you may suggest that at https://github.com/haskell/pvp/issues

**Comment by MaximilianAlgehed** [comment]
Of course, and cabal just does lex ordering... Technically speaking both lex and "assume 0" ordering make sense, but my intuition was definitely assume 0 (to the point where I didn't check and assumed a missing =). That was just lazy and stupid of me.
